//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string JMBG { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string Manager { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> SectorID { get; set; }
    
        public virtual tblGender tblGender { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
