//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string JMBG { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Manager { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public int Expr1 { get; set; }
        public string Gender { get; set; }
        public int Expr2 { get; set; }
        public string Adress { get; set; }
        public string States { get; set; }
        public string Place { get; set; }
        public int Expr3 { get; set; }
        public string SectorName { get; set; }
    }
}
